### ISSUE TITLE
Does not compile the folling test programs on cygwin, gcc version 6.3.0

### ISSUE THREAD

**Issue by JungHong** [jweyrich/p99#2]
I am stuck on cygwin with gcc version 6.3.0  I am hoping that someone will make p99 usable with gcc 6.3.0.  What I was able to see and do with tests/test-p99-blocks.c is really useful to me.  But I would like to see the last four programs below compile and execute before I commit to using p99.

So, please let me know if there is anyone working on the issues having to do with the case error, as listed below.  I am willing to help, but having spent hours reading through the p99/p99*.h, I know I am at my wit's end.

I made some changes and was able to compile and execute the following programs in tests/*.c
test-p99-block.c                                                                                                                       
test-p99-cases.c        
test-p99-classification.c
test-p99-double.c   
test-p99-error.c        
test-p99-ndim.c         
test-p99-pow.c          
test-p99-qualifier.c 
test-p99-rand.c         
test-p99-thread.c   
test-p99-uf.c           
test-p99-va-arg.c

But, I get errors when I try to compile the following four test programs in tests/
test-p99-choice.c       // case
test-p99-compound.c     // case; returns local address
test-p99-fstruct.c      // left shift greater than width of type
test-p99-int.c          // left shift greater than width of type      

The exact error message have to do with the 'case label does not reduce to an int constant':
../p99/p99_choice.h:93:1: note: in expansion of macro ‘P00_UNIQUE_BIT_FUNCTION’
 P00_UNIQUE_BIT_FUNCTION(unsigned, p00_unique_bit_hash_, -1, 6, 64);
 
../p99/p99_choice.h:65:43: error: case label does not reduce to an integer constant
 #define P00_UNIQUE_BIT_RETURN(NAME, X, I) case P00_UNIQUE_BIT_(I, X, NAME): return I
                          
../p99/p99_for.h:111:34: note: in definition of macro ‘P00_SEP’
 #define P00_SEP(NAME, I, REC, X) REC; X
                                
../p99/p99_generated.h:8441:2: note: in expansion of macro ‘P00_SEP’
  OP(NAME, 62, P00_FOR62(NAME, OP, FUNC, P99_ALLBUTLAST(__VA_ARGS__)), FUNC(NAME, P99_LAST(__VA_ARGS__), 62))
 
../p99/p99_generated.h:8441:71: note: in expansion of macro ‘P00_UNIQUE_BIT_RETURN’
  OP(NAME, 62, P00_FOR62(NAME, OP, FUNC, P99_ALLBUTLAST(__VA_ARGS__)), FUNC(NAME, P99_LAST(__VA_ARGS__), 62))
                                                                
../p99/p99_generated.h:8443:15: note: in expansion of macro ‘P00_FOR63’
  OP(NAME, 63, P00_FOR63(NAME, OP, FUNC, P99_ALLBUTLAST(__VA_ARGS__)), FUNC(NAME, P99_LAST(__VA_ARGS__), 63))
 
../p99/p99_paste.h:53:26: note: in expansion of macro ‘P00_FOR64’
 #define P99_CAT2(_1, _2) _1 ## _2

../p99/p99_choice.h:81:5: note: in expansion of macro ‘P99_FOR’
     P99_FOR(WIDTH, WIDTH, P00_SEP, P00_UNIQUE_BIT_RETURN, P99_DUPL(WIDTH, BITS)); \
   
../p99/p99_choice.h:93:1: note: in expansion of macro ‘P00_UNIQUE_BIT_FUNCTION’
 P00_UNIQUE_BIT_FUNCTION(unsigned, p00_unique_bit_hash_, -1, 6, 64);

../p99/p99_choice.h:65:43: error: case label does not reduce to an integer constant
 #define P00_UNIQUE_BIT_RETURN(NAME, X, I) case P00_UNIQUE_BIT_(I, X, NAME): return I
                              
Thanks

**Comment by JungHong** [comment]
This is to record that gcc-6.3.0 passes the c99 conformance test.  The following produces an html page with no missing or faulty: I take that to mean that the preprocessor is ok.  
 
gcc-6.3.0 -Wall -c -o test-p99-conformance.o -std=c99 -fextended-identifiers -Wno-trigraphs -Wno-unused-value -DSKIP_UNIVERSAL_UTF8 -DSKIP_EVALUATED_COMMA_ASSIGN -DSKIP_PRAGMA test-p99-conformance.c

**Comment by JungHong** [comment]
By carefully including only the minimum of the p99_*.h, I was able to compile and execute all but one program.  The program that does not compile at this time is tests/test-p9-choice.c  The problem seems to be in *choice.h, or some other *.h that it needs.
 
If anyone has been able to get past this, please post.  I intend to post when I get all of the test programs to compile using gcc 6.3.0 on cygwin, or if someone shows up and is interested in the in-progress files.

**Comment by JungHong** [comment]
SOLVED:
I was able to compile all  programs in tests/*.c using gcc-6.3.0 on cygwin, but I have not added ctap.h to output the result of tests to see if the output of the tests/*.exe make sense:  currently, they only compile and execute.

The last change that enables *choice.c to compile and execute is in p99/*choice.h.  Sometime between gcc-4.9 and gcc-6.3.0 the definition of _C must have changed.

I'll post the exact change that was required after the ctap.h is added.  But if someone is in a hurry to see the required change, please contact me or post that you need the change right away.

**Comment by jweyrich** [comment]
Please, can you contribute back to the official repository? It's at https://gforge.inria.fr/scm/?group_id=2917.
This repository is just a mirror of the official one.
